---
- name: Get secrets from Vault
  hosts: localhost
  connection: local
  vars:
    token:  "{{ lookup('env','VAULT_TOKEN') }}"
    url: "{{ lookup('env','VAULT_ADDR') }}"


  tasks:
  - name: Return all secrets from a path
    debug:
      msg: "{{ lookup('hashi_vault', 'secret=test/test token={{ token }} url={{ url }}')}}"
